apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-app
  template:
    metadata:
      labels:
        app: bp-app
    spec:
      containers:
      - name: bp-app
        image: faithlisa/bp-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bp-service
spec:
  type: NodePort
  selector:
    app: bp-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
